/**
 * サンプルカード。
 *
 * カードをまだ1枚も作っていない状態でも対戦を試せるよう、
 * 最低限の種類を用意している。
 * 利用者がカードを作れば、そちらが優先される。
 */

import type { Card } from '../types/card';

export const SAMPLE_CARDS: Card[] = [
  {
    id: 'sample_fire_01',
    name: '紅蓮の突撃兵 ブレイズファング',
    nameRuby: 'ぐれんのとつげきへい ぶれいずふぁんぐ',
    cost: 2,
    civilizations: ['fire'],
    power: 2000,
    race: 'ファイア・フェニックス',
    type: 'creature',
    effects: [],
    keywords: { speedAttacker: true },
    rarity: 'N',
    flavor: '速さこそが、最大の火力である。',
  },
  {
    id: 'sample_fire_02',
    name: '業火の竜人 サラマンダー・ロード',
    nameRuby: 'ごうかのりゅうじん さらまんだー・ろーど',
    cost: 5,
    civilizations: ['fire'],
    power: 6000,
    race: 'ドラゴンリンク',
    type: 'creature',
    effects: [],
    keywords: { breakerType: 'W' },
    rarity: 'R',
  },
  {
    id: 'sample_fire_03',
    name: '爆炎の一撃',
    nameRuby: 'ばくえんのいちげき',
    cost: 3,
    civilizations: ['fire'],
    type: 'spell',
    effects: [
      { trigger: 'onSummon', effect: 'destroy', target: 'opponentRandom', value: 1 },
    ],
    keywords: { shieldTrigger: true },
    rarity: 'N',
  },
  {
    id: 'sample_water_01',
    name: '深海の智者 アクア・セージ',
    nameRuby: 'しんかいのちしゃ あくあ・せーじ',
    cost: 3,
    civilizations: ['water'],
    power: 2000,
    race: 'リキッド・ピープル',
    type: 'creature',
    effects: [{ trigger: 'onSummon', effect: 'draw', target: 'self', value: 1 }],
    keywords: {},
    rarity: 'N',
  },
  {
    id: 'sample_water_02',
    name: '氷結の巨人 フロストタイタン',
    nameRuby: 'ひょうけつのきょじん ふろすとたいたん',
    cost: 6,
    civilizations: ['water'],
    power: 7000,
    race: 'アイス・フォーム',
    type: 'creature',
    effects: [],
    keywords: { blocker: true },
    rarity: 'SR',
    flavor: '凍てつく壁は、何者も通さない。',
  },
  {
    id: 'sample_light_01',
    name: '聖なる守護者 ホーリーガーディアン',
    nameRuby: 'せいなるしゅごしゃ ほーりーがーでぃあん',
    cost: 4,
    civilizations: ['light'],
    power: 3000,
    race: 'エンジェル・コマンド',
    type: 'creature',
    effects: [],
    keywords: { blocker: true },
    rarity: 'N',
  },
  {
    id: 'sample_light_02',
    name: '浄化の光',
    nameRuby: 'じょうかのひかり',
    cost: 2,
    civilizations: ['light'],
    type: 'spell',
    effects: [
      { trigger: 'onSummon', effect: 'untap', target: 'ownCreatures', value: 1 },
    ],
    keywords: { shieldTrigger: true },
    rarity: 'N',
  },
  {
    id: 'sample_dark_01',
    name: '闇夜の刺客 シャドウアサシン',
    nameRuby: 'やみよのしかく しゃどうあさしん',
    cost: 3,
    civilizations: ['darkness'],
    power: 2500,
    race: 'デーモン',
    type: 'creature',
    effects: [
      { trigger: 'onSummon', effect: 'discard', target: 'opponent', value: 1 },
    ],
    keywords: { slayer: true },
    rarity: 'R',
  },
  {
    id: 'sample_dark_02',
    name: '冥府の支配者 デス・エンペラー',
    nameRuby: 'めいふのしはいしゃ です・えんぺらー',
    cost: 7,
    civilizations: ['darkness'],
    power: 8000,
    race: 'デーモン・コマンド',
    type: 'creature',
    effects: [],
    keywords: { breakerType: 'T' },
    rarity: 'VR',
    flavor: '終わりは、いつも静かに訪れる。',
  },
  {
    id: 'sample_nature_01',
    name: '疾風のフェアリー',
    nameRuby: 'しっぷうのふぇありー',
    cost: 1,
    civilizations: ['nature'],
    power: 1000,
    race: 'フェアリー・ライフ',
    type: 'creature',
    effects: [{ trigger: 'onSummon', effect: 'toMana', target: 'self', value: 1 }],
    keywords: {},
    rarity: 'N',
  },
  {
    id: 'sample_nature_02',
    name: '巨木の番人 フォレストガーディアン',
    nameRuby: 'きょぼくのばんにん ふぉれすとがーでぃあん',
    cost: 5,
    civilizations: ['nature'],
    power: 5000,
    race: 'アース・ドラゴン',
    type: 'creature',
    effects: [],
    keywords: { blocker: true },
    rarity: 'N',
  },
  {
    id: 'sample_nature_03',
    name: '生命の息吹',
    nameRuby: 'せいめいのいぶき',
    cost: 3,
    civilizations: ['nature'],
    type: 'spell',
    effects: [{ trigger: 'onSummon', effect: 'draw', target: 'self', value: 2 }],
    keywords: {},
    rarity: 'N',
  },
  {
    id: 'sample_multi_01',
    name: '紅魔の破壊王 インフェルノデーモン',
    nameRuby: 'こうまのはかいおう いんふぇるのでーもん',
    cost: 6,
    civilizations: ['fire', 'darkness'],
    power: 6500,
    race: 'デーモン',
    type: 'creature',
    effects: [
      { trigger: 'onSummon', effect: 'destroy', target: 'chosenOpponent', value: 1 },
    ],
    keywords: { breakerType: 'W' },
    rarity: 'SR',
    flavor: '二つの力が交わる時、災厄が生まれる。',
  },
];
